# Generated by Django 6.0.4 on 2026-05-07 18:18

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AmenityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nama Fasilitas')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Icon/Emoji')),
                ('description', models.TextField(blank=True, verbose_name='Deskripsi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tipe Fasilitas',
                'verbose_name_plural': 'Tipe Fasilitas',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_code', models.CharField(default='TEMP', max_length=20, unique=True, verbose_name='Kode Booking')),
                ('booking_date', models.DateField(verbose_name='Tanggal Booking')),
                ('start_time', models.TimeField(verbose_name='Jam Mulai')),
                ('end_time', models.TimeField(verbose_name='Jam Selesai')),
                ('status', models.CharField(choices=[('pending', 'Menunggu Persetujuan'), ('approved', 'Disetujui'), ('rejected', 'Ditolak'), ('cancelled', 'Dibatalkan'), ('completed', 'Selesai')], default='pending', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, verbose_name='Catatan')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Harga')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='booking_attachments/', verbose_name='Lampiran')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='Pemesan')),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Booking',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(default='TEMP', max_length=50, unique=True, verbose_name='Nomor Invoice')),
                ('company', models.CharField(blank=True, max_length=200, verbose_name='Perusahaan')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Jumlah')),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Pajak')),
                ('total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total')),
                ('description', models.TextField(blank=True, verbose_name='Deskripsi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='core.booking', verbose_name='Booking')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoice',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('booking_pending', 'Booking Tertunda'), ('booking_approved', 'Booking Disetujui'), ('booking_rejected', 'Booking Ditolak'), ('booking_cancelled', 'Booking Dibatalkan'), ('payment_reminder', 'Reminder Pembayaran'), ('payment_verified', 'Pembayaran Terverifikasi'), ('payment_rejected', 'Pembayaran Ditolak')], max_length=30, verbose_name='Tipe')),
                ('channel', models.CharField(choices=[('in_app', 'Dalam Aplikasi'), ('email', 'Email'), ('sms', 'SMS')], default='in_app', max_length=20, verbose_name='Saluran')),
                ('title', models.CharField(max_length=200, verbose_name='Judul')),
                ('message', models.TextField(verbose_name='Pesan')),
                ('is_read', models.BooleanField(default=False, verbose_name='Sudah Dibaca')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Dibaca Pada')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Dikirim Pada')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.booking', verbose_name='Booking')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Notifikasi',
                'verbose_name_plural': 'Notifikasi',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.EmailField(max_length=254, verbose_name='Penerima')),
                ('subject', models.CharField(max_length=200, verbose_name='Subjek')),
                ('body', models.TextField(verbose_name='Isi Email')),
                ('status', models.CharField(default='pending', max_length=20, verbose_name='Status')),
                ('error_message', models.TextField(blank=True, verbose_name='Pesan Error')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Dikirim Pada')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_notification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.notification', verbose_name='Notifikasi Terkait')),
            ],
            options={
                'verbose_name': 'Log Email',
                'verbose_name_plural': 'Log Email',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notifications', models.BooleanField(default=True, verbose_name='Notifikasi Email')),
                ('sms_notifications', models.BooleanField(default=False, verbose_name='Notifikasi SMS')),
                ('in_app_notifications', models.BooleanField(default=True, verbose_name='Notifikasi Dalam Aplikasi')),
                ('booking_status_updates', models.BooleanField(default=True, verbose_name='Update Status Booking')),
                ('payment_reminders', models.BooleanField(default=True, verbose_name='Reminder Pembayaran')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Preferensi Notifikasi',
                'verbose_name_plural': 'Preferensi Notifikasi',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Jumlah')),
                ('method', models.CharField(choices=[('cash', 'Tunai'), ('transfer', 'Transfer Bank'), ('card', 'Kartu Kredit'), ('gateway', 'Payment Gateway')], max_length=20, verbose_name='Metode Pembayaran')),
                ('status', models.CharField(choices=[('pending', 'Menunggu Pembayaran'), ('verified', 'Terverifikasi'), ('rejected', 'Ditolak'), ('refunded', 'Dikembalikan')], default='pending', max_length=20, verbose_name='Status')),
                ('proof', models.ImageField(blank=True, null=True, upload_to='payment_proofs/', verbose_name='Bukti Pembayaran')),
                ('notes', models.TextField(blank=True, verbose_name='Catatan')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Waktu Verifikasi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='core.booking', verbose_name='Booking')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_payments', to=settings.AUTH_USER_MODEL, verbose_name='Diverifikasi oleh')),
            ],
            options={
                'verbose_name': 'Pembayaran',
                'verbose_name_plural': 'Pembayaran',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nama Ruangan')),
                ('location', models.CharField(max_length=100, verbose_name='Lokasi')),
                ('capacity', models.PositiveIntegerField(verbose_name='Kapasitas')),
                ('description', models.TextField(blank=True, verbose_name='Deskripsi')),
                ('price_per_hour', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Harga per Jam')),
                ('is_available', models.BooleanField(default=True, verbose_name='Tersedia')),
                ('status', models.CharField(choices=[('active', 'Aktif'), ('maintenance', 'Maintenance'), ('inactive', 'Tidak Aktif')], default='active', max_length=20, verbose_name='Status')),
                ('image', models.ImageField(blank=True, null=True, upload_to='rooms/', verbose_name='Gambar Ruangan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amenities', models.ManyToManyField(blank=True, to='core.amenitytype', verbose_name='Fasilitas')),
            ],
            options={
                'verbose_name': 'Ruangan',
                'verbose_name_plural': 'Ruangan',
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='core.room', verbose_name='Ruangan'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='Nomor Telepon')),
                ('company', models.CharField(blank=True, max_length=100, verbose_name='Perusahaan')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='Departemen')),
                ('address', models.TextField(blank=True, verbose_name='Alamat')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Kota')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Avatar')),
                ('role', models.CharField(choices=[('user', 'User'), ('staff', 'Staff'), ('admin', 'Admin')], default='user', max_length=20, verbose_name='Role')),
                ('is_email_verified', models.BooleanField(default=False, verbose_name='Email Terverifikasi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil User',
                'verbose_name_plural': 'Profil User',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Rating')),
                ('comment', models.TextField(blank=True, verbose_name='Komentar')),
                ('helpful_count', models.PositiveIntegerField(default=0, verbose_name='Jumlah Membantu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review', to='core.booking', verbose_name='Booking')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='Pengguna')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.room', verbose_name='Ruangan')),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Review',
                'unique_together': {('user', 'room')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('room', 'booking_date', 'start_time', 'end_time')},
        ),
        migrations.CreateModel(
            name='BlackoutDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Tanggal')),
                ('reason', models.CharField(blank=True, max_length=200, verbose_name='Alasan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blackout_dates', to='core.room', verbose_name='Ruangan')),
            ],
            options={
                'verbose_name': 'Tanggal Libur',
                'verbose_name_plural': 'Tanggal Libur',
                'unique_together': {('room', 'date')},
            },
        ),
        migrations.CreateModel(
            name='RoomAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Senin'), (1, 'Selasa'), (2, 'Rabu'), (3, 'Kamis'), (4, 'Jumat'), (5, 'Sabtu'), (6, 'Minggu')], verbose_name='Hari')),
                ('opening_time', models.TimeField(default='08:00', verbose_name='Jam Buka')),
                ('closing_time', models.TimeField(default='17:00', verbose_name='Jam Tutup')),
                ('is_available', models.BooleanField(default=True, verbose_name='Tersedia')),
                ('min_booking_hours', models.PositiveIntegerField(default=1, verbose_name='Min Jam Booking')),
                ('max_booking_hours', models.PositiveIntegerField(default=8, verbose_name='Max Jam Booking')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_rules', to='core.room', verbose_name='Ruangan')),
            ],
            options={
                'verbose_name': 'Ketersediaan Ruangan',
                'verbose_name_plural': 'Ketersediaan Ruangan',
                'unique_together': {('room', 'day_of_week')},
            },
        ),
    ]
