# Generated by Django 6.0.4 on 2026-05-11 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Menunggu Pembayaran'), ('verified', 'Terverifikasi'), ('rejected', 'Ditolak'), ('refunding', 'Sedang Diproses Refund'), ('refunded', 'Dikembalikan (Selesai)')], default='pending', max_length=20, verbose_name='Status'),
        ),
    ]
