# Generated by Django 6.0.4 on 2026-05-11 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_payment_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailLog',
        ),
    ]
