# Generated by Django 6.0.4 on 2026-05-11 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_delete_emaillog'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nama Lengkap'),
        ),
    ]
