# Generated by Django 6.0.4 on 2026-05-11 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_userprofile_city_remove_userprofile_company_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='company',
        ),
        migrations.RemoveField(
            model_name='review',
            name='helpful_count',
        ),
    ]
